apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
 name: objectdetection
spec:
 selector:
  matchLabels:
   app: objectdetection
 replicas: 3
 template:
  metadata:
   labels:
    app: objectdetection
  spec:
   containers:
   - name: objectdetection
     image: onkar13/object_detection:latest
     ports:
     - containerPort: 5000
     resources:
      limits:
       cpu: "0.5"
      requests:
       cpu: "0.5"
