apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
 name: objectdetection
spec:
 selector:
  matchLabels:
   app: objectdetection
 replicas: 1 # tells deployment to run 2 pods matching the template
 template:
  metadata:
   labels:
    app: objectdetection
  spec:
   containers:
   - name: objectdetection
     image: onkar13/object_detection:latest
     ports:
     - containerPort: 5000
