apiVersion: v1
kind: Service
metadata:
 name: objectdetection-service
spec:
 type: NodePort    
 selector:
  app: objectdetection
 ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 31268
